<a href="https://colab.research.google.com/github/Sam-Gyu/Python-for-dataScience/blob/main/Python_for_dataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basics of Python

In [ ]:
fr = ["apple", "banana", "strawbarry"]
print(fr[0])
print(fr[0:2])
fr.append("orange")
fr.insert(1,"mango")
print(fr)
fr.remove("banana")
fr.pop()
print(fr)

apple
['apple', 'banana']
['apple', 'mango', 'banana', 'strawbarry', 'orange']
['apple', 'mango', 'strawbarry']

In [ ]:
coordinates =(10, 20)
print(coordinates[0])

10

In [ ]:
uniquenum = {1,2,3,4}
print(uniquenum)
uniquenum.add(5)
print(uniquenum)
uniquenum.remove(2)
print(uniquenum)

set_a={1,2,3}
set_b={3,5,6}
print(set_a | set_b)  # Union: {1, 2, 3, 4, 5}
print(set_a & set_b)  # Intersection: {3}
print(set_a - set_b)  # Difference: {1, 2}

{1, 2, 3, 4}
{1, 2, 3, 4, 5}
{1, 3, 4, 5}
{1, 2, 3, 5, 6}
{3}
{1, 2}

In [ ]:
student = {"name": "alice", "age": 20, "courses": ["math", "science"]}
print(student["name"])
print(student["courses"][0])
print(student["courses"][1])
student["age"] = 21
print(student)
student["grade"] = 'A'
print(student)

student.pop("age")
print(student)

alice
math
science
{'name': 'alice', 'age': 21, 'courses': ['math', 'science']}
{'name': 'alice', 'age': 21, 'courses': ['math', 'science'], 'grade': 'A'}
{'name': 'alice', 'courses': ['math', 'science'], 'grade': 'A'}

In [ ]:
num=-1
if num > 0:
  print("positive")
elif num < 0:
  print("negative")
else:
  print("zero")

negative

In [ ]:
fr = ["apple", "banana", "strawbarry"]

if "banana" not in fr:
  print("true")
else:
  print("false")

false

In [ ]:
result = None
if result is None:
    print("Result is not set yet.")

Result is not set yet.

In [ ]:
list = []
if list:
  print ("list is not empty")
else:
  print("list is empty")

list is empty

In [ ]:
ismember = True
hasdiscount = False
if hasdiscount:
  if ismember:
    print("you get 20% discount")
  else:
    print("you get 10% discount")
else:
  print("no discount avilable")

no discount avilable

In [ ]:
balance = 500
withdraw_amount = 0
if balance >= withdraw_amount:
  if withdraw_amount > 0:
    print("transaction successful")
  else:
    print("withdraw amount not valid")
else :
  print("balance is less than the withdraw amount")

withdraw amount not valid

In [ ]:
fr = ["apple", "banana", "strawbarry"]
for f in fr:
  print(f)

for i in range(5):
  print(i)

word = "python"
for char in word:
  print (char)

for i in range(3):
  print(i)
else:
  print("loop finished successfuly")

apple
banana
strawbarry
0
1
2
3
4
p
y
t
h
o
n
0
1
2
loop finished successfuly

In [ ]:
for i in range(1,4):  # range from 1 to 4
  for j in range(1,4):
    print (f"{i} * {j} = {i*j}")

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9

In [ ]:
count =0
while count <= 5:
  print (count)
  count+=1

0
1
2
3
4
5

In [ ]:
count = 0
while count <= 10:
  print (count)
  if count == 5 :
    break
  count+=1

0
1
2
3
4
5

In [ ]:
count = 0
while count < 5:
    count += 1
    if count == 3:
        continue
    print(count)

1
2
4
5

In [ ]:
while True:
  response = input("type exit to quit: ")
  if response == 'exit':
    break

type exit to quit: exit

In [ ]:
numbers = [3, 5, 2, 8, 1, 9, 4]
max_value = numbers[0]
for i in range(len(numbers)):
  if numbers[i] > max_value:
    max_value = numbers[i]
    i+=1
print (f"max value = {max_value}")

max value = 9

In [ ]:
numbers = [3, 5, 2, 8, 1, 9, 4]
max_vlaue = numbers[0]
for num in numbers:
  if num > max_value:
    max_value = num
print (f"max value = {max_value}")

max value = 9

In [ ]:
text = "Hello, how are you?"
vowel_count = 0
for char in text:
  if char.lower() in "aouei":
    vowel_count+=1
print (f"vowel count = {vowel_count}")

vowel count = 7

In [ ]:
start = 10
end = 20

for num in range(start, end + 1):
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                break
        else:
            print(num, "is a prime number")

11 is a prime number
13 is a prime number
17 is a prime number
19 is a prime number

In [ ]:
start = 10
end = 20
for num in range (start, end +1):
  if num > 1:
    for i in range(2, num):
      if num%i ==0:
        break
    else:
            print(num, "is a prime number")

11 is a prime number
13 is a prime number
17 is a prime number
19 is a prime number

In [ ]:
n=5
a,b = 0,1
fibseq=[]
while len(fibseq)<n:
  fibseq.append(a)
  temp = a
  a = b
  b = temp+b
print (fibseq)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [ ]:
balance = 1000
while balance > 0:
  withdraw = int(input("enter the amount of withdraw: "))
  if withdraw<= balance:
    balance-= withdraw
    print(f"withdraw successful. remaining balance = {balance}")
  else:
    print ("withdraw is greater than balance. Enter valid withdraw: ")
  if balance == 0:
    print ("balance is zero")
    break

enter the amount of withdraw: 1000
withdraw successful. remaining balance = 0
balance is zero

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
common =[]
for item1 in list1:
  for item2 in list2:
    if item1 == item2:
      common.append(item1)
print(common)

[4, 5]

In [ ]:
num = 5
factorial = 1

for i in range(1, num + 1):
    factorial *= i

print("Factorial of", num, "is", factorial)

Factorial of 5 is 120

In [ ]:
while True:
  user_input = input("please enter number greater that 10: ")
  if user_input.isdigit() and int(user_input)>10:
    print("thank you")
    break
  else:
    print("invalid input.")

please enter number greater that 10: 1
invalid input.
please enter number greater that 10: 20
thank you

In [ ]:
number = 1234
sum = 0
for char in str(number):
  sum += int(char)
print(sum)

10

In [ ]:
rows = 5

for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print("*", end=" ")
    print("")

*
* *
* * *
* * * *
* * * * *

In [ ]:
word = "madam"
is_palindrome = True
left = 0
right = len(word) -1
while left < right:
  if word[left] != word[right]:
    is_palindrome = False
    break
  left+=1
  right-=1
if is_palindrome:
  print("the word is a palindrome")
else:
  print("the word is not palindrome")

the word is not palindrome

In [ ]:
keys = ["name", "age", "location"]
values = ["Alice", 30, "New York"]
dic={}
for i in range(len(keys)):
  dic[keys[i]] = values[i]
print(dic)

{'name': 'Alice', 'age': 30, 'location': 'New York'}

In [ ]:
correct_password = "python123"
attempts = 3

while attempts > 0:
    password = input("Enter your password: ")
    if password == correct_password:
        print("Access granted.")
        break
    else:
        attempts -= 1
        print(f"Incorrect password. You have {attempts} attempts left.")
else:
    print("Access denied. You have used all attempts.")

Enter your password: h
Incorrect password. You have 2 attempts left.
Enter your password: u
Incorrect password. You have 1 attempts left.
Enter your password: t]
Incorrect password. You have 0 attempts left.
Access denied. You have used all attempts.

In [ ]:
correct_password = "python123"
attempts = 3
while attempts >0:
  passw = input("enter you password: ")
  if passw == correct_password:
    print("password is correct")
    break
  else:
    attempts-=1
    print(f"incorrect password. now you have {attempts} attempts")
else:
  print("your all attempts are used ")

enter you password: python123
password is correct

In [ ]:
number = 7
limit = 10

for i in range (limit+1):
  print(f"{number} * {i} = {number*i}")

7 * 0 = 0
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70

In [ ]:
def greet():
  print("hello")
greet()

#######################

def add(a, b):
    return a + b

result = add(5, 3)
print("Sum:", result)

#######################

def greet(name ="guest"):
  print(f"hello {name}")
greet()

#######################

def divide(a, b):
  quotient = a // b
  remainder = a % b
  return quotient, remainder
q, r = divide(10, 3)
print ("quotient = ", q)
print ("remainder = ", r)

#######################

def multiply(a, b):
    """
    Multiplies two numbers and returns the result.
    """
    return a * b

print(multiply(4, 5))
print(multiply.__doc__)

hello
Sum: 8
hello guest
quotient =  3
remainder =  1
20

    Multiplies two numbers and returns the result.

In [ ]:
square = lambda x: x ** 2
print(square(4))

#######################

multiply = lambda x,y : x*y
print(multiply(2,3))

#######################

numbers = [1,2,3,4,5]
squares = map(lambda x: x**2 , numbers)
print(list(squares))

#######################

nums = [1,2,3,4,5,6]
even_nums = filter(lambda x : x%2 == 0, nums)
print(list(even_nums))

#######################

def fibonacci(n):
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

print(fibonacci(5))

#######################

def apply_operation (a,b,operation):
  return operation(a, b)
def add(a, b):
  return a + b
print (apply_operation(5,5, add))

16
6
[1, 4, 9, 16, 25]
[2, 4, 6]
5
10

In [ ]:
def calc_avg(nums):
  return sum(nums) / len(nums)
nums = [10,20,30,40,50]
print("average= ", calc_avg(nums))

#######################

def find_longest(words):
  longest = ""
  for word in words:
    if len(word)> len(longest):
      longest = word
  return longest
words = ["apple", "banana", "cherry", "date"]
print ("longest word:", find_longest(words))

#######################

def isprime(n):
    if n < 2:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

print(isprime(6))

#######################

def square(nums):
    sqr = []
    for x in nums:
        x = x**2
        sqr.append(x)
    return sqr

nums = [1,2,3,4,5]
print(square(nums))

#######################

def square_list(numbers):
    return [x ** 2 for x in numbers]

numbers = [1, 2, 3, 4, 5]
print("List of squares:", square_list(numbers))

#######################

def toupper(words):
  return [word.upper() for word in words]

words = ["hello", "world", "python", "functions"]
print("Uppercase words:", toupper(words))

#######################

def calculate_total_price(prices, tax_rate):
    total = sum(prices)
    totalwithtax = total * (1+tax_rate)
    return totalwithtax

prices = [100, 200, 300]
tax_rate = 0.1
print ("total price = ", calculate_total_price(prices, tax_rate))

#######################

def find_min_max(numbers):
  min = numbers[0]
  max = numbers[0]
  for num in numbers:
    if num < min:
      min = num
    if num > max:
      max = num
  return min, max

numbers = [3, 7, 2, 9, 4]
a,b = find_min_max(numbers)
print (a, b)

#######################

def find_min_max(numbers):
    return min(numbers), max(numbers)

numbers = [3, 7, 2, 9, 4]
min_value, max_value = find_min_max(numbers)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

#######################

def is_valid_email(email):
    # Check two conditions:
    # 1) "@" must exist in the email
    # 2) There must be a "." in the part after "@"
    # The function returns True only if both conditions are True
    return "@" in email and "." in email.split("@")[-1]
    # "example@example.com".split("@") = ["example", "example.com"]
    # email.split("@")[-1] = "example.com" # the last element in the list

email = "example@example.com"
print("Is valid email:", is_valid_email(email))

#######################

def countfreq(text):
  freq = {}
  for char in text:
    if char in freq:
      freq[char]+=1
    else:
      freq[char] = 1
  return freq
text = "sama waleed"
print ("frequency of each char: ", countfreq(text))

#######################

def isvalidemail(email):
  return "@" in email and '.' in email.split("@")[-1]

email = "example@example.com"
print("Is valid email:", is_valid_email(email))

average=  30.0
longest word: banana
False
[1, 4, 9, 16, 25]
List of squares: [1, 4, 9, 16, 25]
Uppercase words: ['HELLO', 'WORLD', 'PYTHON', 'FUNCTIONS']
total price =  660.0
2 9
Minimum value: 2
Maximum value: 9
Is valid email: True
frequency of each char:  {'s': 1, 'a': 3, 'm': 1, ' ': 1, 'w': 1, 'l': 1, 'e': 2, 'd': 1}
Is valid email: False

# OOP

In [ ]:
class Person:
    # Constructor method to initialize attributes
    def __init__(self, name, age):
        self.name = name  # Attribute 'name'
        self.age = age    # Attribute 'age'

    # Method to display the person's details
    def display_info(self):
        return(f"Name: {self.name}, Age: {self.age}")

# Creating an object of the Person class
person1 = Person("Alice", 30)

# Accessing object attributes and methods
print(person1.name)  # Output: Alice
print(person1.age)   # Output: 30
print(person1.display_info())  # Output: Name: Alice, Age: 30

Alice
30
Name: Alice, Age: 30

In [ ]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} says woof!")

# Creating multiple Dog objects
dog1 = Dog("Buddy", "Golden Retriever")
dog2 = Dog("Lucy", "Labrador")

# Calling methods on different objects
dog1.bark()  # Output: Buddy says woof!
dog2.bark()  # Output: Lucy says woof!
print(dog2.name)
print(dog1.breed)

Buddy says woof!
Lucy says woof!
Lucy
Golden Retriever

In [ ]:
class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year

    def start(self):
        print(f"The {self.year} {self.make} {self.model} is starting.")

    def stop(self):
        print(f"The {self.year} {self.make} {self.model} is stopping.")

# Creating an object of the Car class
my_car = Car("Toyota", "Camry", 2020)
print(my_car.make)
print(my_car.model)
print(my_car.year)

# Calling methods on the object
my_car.start()  # Output: The 2020 Toyota Camry is starting.
my_car.stop()   # Output: The 2020 Toyota Camry is stopping.

Toyota
Camry
2020
The 2020 Toyota Camry is starting.
The 2020 Toyota Camry is stopping.

In [ ]:
class Student:
    def __init__(self, name, grade):
        self.name = name
        self.grade = grade

    def update_grade(self, new_grade):
        self.grade = new_grade

    def display_info(self):
        print(f"Student: {self.name}, Grade: {self.grade}")

# Creating a Student object
student1 = Student("Sama", "B")
student1.display_info()  # Output: Student: John, Grade: B

# Updating the student's grade
student1.update_grade("A")
student1.display_info()  # Output: Student: John, Grade: A

Student: Sama, Grade: B
Student: Sama, Grade: A

In [ ]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def get_description(self):
        return f"'{self.title}' by {self.author}"

# Creating a Book object
book1 = Book("1984", "George Orwell")

# Using a method to get information about the book
description = book1.get_description()
print(description)  # Output: '1984' by George Orwell

'1984' by George Orwell

In [ ]:
class Product:
    def __init__(self, name, price, quantity):
        self.name = name
        self.price = price
        self.quantity = quantity

    def restock(self, amount):
        self.quantity += amount
        print(f"Restocked {self.name}. New quantity: {self.quantity}")

    def sell(self, amount):
        if amount <= self.quantity:
            self.quantity -= amount
            print(f"Sold {amount} of {self.name}. Remaining quantity: {self.quantity}")
        else:
            print("Not enough stock to sell.")

# Example usage
product1 = Product("Laptop", 1200, 10)
product1.restock(5)   # Output: Restocked Laptop. New quantity: 15
product1.sell(3)      # Output: Sold 3 of Laptop. Remaining quantity: 12
product1.sell(20)     # Output: Not enough stock to sell.

Restocked Laptop. New quantity: 15
Sold 3 of Laptop. Remaining quantity: 12
Not enough stock to sell.

In [ ]:
class Calculator:
    def add(self, a, b):
        return a + b

    def subtract(self, a, b):
        return a - b

    def multiply(self, a, b):
        return a * b

    def divide(self, a, b):
        if b != 0:
            return a / b
        else:
            return "Error: Division by zero."

# Example usage
calc = Calculator()
print(calc.add(10, 5))       # Output: 15
print(calc.subtract(10, 5))  # Output: 5
print(calc.multiply(10, 5))  # Output: 50
print(calc.divide(10, 2))    # Output: 5.0
print(calc.divide(10, 0))    # Output: Error: Division by zero.

15
5
50
5.0
Error: Division by zero.

In [ ]:
class Student:
    def __init__(self, name, student_id):
        self.name = name
        self.student_id = student_id
        self.courses = []

    def enroll(self, course):
        self.courses.append(course)
        print(f"{self.name} has enrolled in {course}")

    def display_info(self):
        print(f"Student: {self.name}, ID: {self.student_id}, Courses: {', '.join(self.courses)}")

# Example usage
student1 = Student("John Doe", "S12345")
student1.enroll("Math")
student1.enroll("Science")
student1.display_info()  # Output: Student: John Doe, ID: S12345, Courses: Math, Science

John Doe has enrolled in Math
John Doe has enrolled in Science
Student: John Doe, ID: S12345, Courses: Math, Science

In [ ]:
class BankAccount:
    def __init__(self, account_holder, balance=0):
        self.account_holder = account_holder
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited {amount}. New balance: {self.balance}")

    def withdraw(self, amount):
        if amount <= self.balance:
            self.balance -= amount
            print(f"Withdrew {amount}. Remaining balance: {self.balance}")
        else:
            print("Insufficient funds.")

# Example usage
account = BankAccount("Alice")
account.deposit(1000)   # Output: Deposited 1000. New balance: 1000
account.withdraw(500)   # Output: Withdrew 500. Remaining balance: 500
account.withdraw(1000)  # Output: Insufficient funds.

Deposited 1000. New balance: 1000
Withdrew 500. Remaining balance: 500
Insufficient funds.

In [ ]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def display(self):
        print(f"Title: {self.title}, Author: {self.author}")

class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):  # book is and object of class Book
        self.books.append(book)
        print(f"Added book: {book.title}")

    def list_books(self):
        print("Library books:")
        for book in self.books:
            book.display()

# Example usage
book1 = Book("1984", "George Orwell")
book2 = Book("To Kill a Mockingbird", "Harper Lee")
library = Library()
library.add_book(book1)  # Output: Added book: 1984
library.add_book(book2)  # Output: Added book: To Kill a Mockingbird
library.list_books()

Added book: 1984
Added book: To Kill a Mockingbird
Library books:
Title: 1984, Author: George Orwell
Title: To Kill a Mockingbird, Author: Harper Lee

In [ ]:
class Candidate:
    def __init__(self, name):
        self.name = name
        self.votes = 0

    def add_vote(self):
        self.votes += 1

    def display(self):
        print(f"Candidate: {self.name}, Votes: {self.votes}")

# Example usage
candidate1 = Candidate("Alice")
candidate2 = Candidate("Bob")

# Voting
candidate1.add_vote()
candidate1.add_vote()
candidate2.add_vote()

# Display results
candidate1.display()  # Output: Candidate: Alice, Votes: 2
candidate2.display()  # Output: Candidate: Bob, Votes: 1

Candidate: Alice, Votes: 2
Candidate: Bob, Votes: 1

In [ ]:
class Car:
    def __init__(self, make, model, year):
        self.make = make
        self.model = model
        self.year = year
        self.is_rented = False

    def rent(self):
        if not self.is_rented:
            self.is_rented = True
            print(f"{self.make} {self.model} rented.")
        else:
            print(f"{self.make} {self.model} is already rented.")

    def return_car(self):
        if self.is_rented:
            self.is_rented = False
            print(f"{self.make} {self.model} returned.")
        else:
            print(f"{self.make} {self.model} was not rented.")

# Example usage
car1 = Car("Toyota", "Corolla", 2020)
car1.rent()       # Output: Toyota Corolla rented.
car1.rent()       # Output: Toyota Corolla is already rented.
car1.return_car() # Output: Toyota Corolla returned.
car1.return_car() # Output: Toyota Corolla was not rented.

Toyota Corolla rented.
Toyota Corolla is already rented.
Toyota Corolla returned.
Toyota Corolla was not rented.

# Numpy

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # Output: [1 2 3 4 5]


arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)


zeros = np.zeros((2,4))
print (zeros)


ones = np.ones((3,2))
print(ones)


range_array = np.arange(10)
print(range_array)  # Output: [0 1 2 3 4 5 6 7 8 9]



# We use np.linspace to generate numbers that are evenly spaced
# linspace(start, stop, num) → start: first number, stop: last number, num: total numbers

# Here we want 5 numbers between 0 and 1
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)
# Why only 3 numbers in between?
# Because the start (0) and stop (1) are counted as part of the 5 numbers
# So the 5 numbers are: 0, ?, ?, ?, 1 → 3 numbers in between

# Step size calculation:
# step = (stop - start) / (num - 1)
# step = (1 - 0) / (5 - 1) = 0.25

# Therefore the numbers are: 0, 0.25, 0.5, 0.75, 1

# Difference from np.arange:
# arange uses a step size you specify, while linspace specifies total number of points



random_array = np.random.rand(3, 3)  # 3*3 matrix with random numbers from 0 to 1
print(random_array)


random_integers = np.random.randint(1, 10, (2, 2)) # Creating an Array with Random Integers. (start, end, (matrix size))
print(random_integers)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]
[[0.46579583 0.37064162 0.77241141]
 [0.9426301  0.29589084 0.07261823]
 [0.71244796 0.4682123  0.6042351 ]]
[[2 5]
 [5 5]]

In [ ]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3.shape)  # Output: (2, 3)
print(arr3.dtype)  # Output: int64
print(arr3[0:,0:2])

arr4 = np.array([1,2,3,4,5])
print(arr4[0])
print(arr4[-1]) # last element
print(arr4[1:4])  # Output: [2 3 4] #(4) not included

arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr5[0, 2])  # Output: 3

print(arr5[1:, 1:])  # Output: [[5 6]
                     #          [8 9]]


arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])
print(arr6 + arr7)  # Output: [5 7 9]



arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)  # Output: [[11 12 13]
                 #          [14 15 16]]


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))  # Output: [[19 22]
                           #          [43 50]]


arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0
print(np.sum(arr))   # Output: 15
print(np.min(arr))
print(np.max(arr))

(2, 3)
int64
[[1 2]
 [4 5]]
1
5
[2 3 4]
3
[[5 6]
 [8 9]]
[5 7 9]
[[11 12 13]
 [14 15 16]]
[[19 22]
 [43 50]]
3.0
15
1
5

# Numpy Practical Applications

In [ ]:
square_matrix = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
print("Square Matrix:\n", square_matrix)


diagonal_matrix = np.diag([1,2,4])
print("Diagonal Matrix:\n", diagonal_matrix)

identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)


symmetric_matrix = np.array([[1, 2, 3],
                             [2, 5, 6],
                             [3, 6, 9]])
print("Symmetric Matrix:\n", symmetric_matrix)


matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
transpose_matrix = np.transpose(matrix)
print("Original Matrix:\n", matrix)
print("Transpose of Matrix:\n", transpose_matrix)


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
trace = np.trace(matrix)
print("Trace of Matrix:", trace)


matrix = np.array([[4, 6],
                   [3, 8]])
determinant = np.linalg.det(matrix)
print("Determinant of Matrix:", determinant)


matrix = np.array([[1, 2],
                   [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of Matrix:\n", inverse_matrix)


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
rank = np.linalg.matrix_rank(matrix)
print("Rank of Matrix:", rank)

Square Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 4]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Symmetric Matrix:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]
Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose of Matrix:
 [[1 4]
 [2 5]
 [3 6]]
Trace of Matrix: 15
Determinant of Matrix: 14.000000000000004
Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Rank of Matrix: 2

# Data Manipulation with Pandas

In [ ]:
import pandas as pd

# Creating a Series from a list
series = pd.Series([10, 20, 30, 40, 50])
print(series)
temps = pd.Series([32, 35, 30], index=['Mon', 'Tue', 'Wed'])
print(temps)  # Output: 35

0    10
1    20
2    30
3    40
4    50
dtype: int64
Mon    32
Tue    35
Wed    30
dtype: int64

In [ ]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
print(df)

print ('\n')

df.head()

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [ ]:
df.describe()

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [ ]:
print(df['Name'])

print(df['Age'])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64

In [ ]:
# Filtering Rows Based on Condition
# df['Age'] > 30 creates True/False for each row
# df[...] selects only the rows where True
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age     City
2  Charlie   35  Chicago
      Name  Age     City
2  Charlie   35  Chicago

In [ ]:
# Selecting Specific Rows and Columns
# select specific rows and columns. Here, rows with indices 0 and 1 and columns 'Name' and 'City' are selected.
selected_data = df.loc[0:1, ['Name', 'City']]
print(selected_data)

    Name         City
0  Alice     New York
1    Bob  Los Angeles
    Name  Age
0  Alice   25
1    Bob   30

In [ ]:
# Adding a New Column
df['Salary'] = [70000, 80000, 90000]
print(df)

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000

In [ ]:
# Updating Column Values
df['Age'] = df['Age']+1
print(df)

      Name  Age         City  Salary
0    Alice   26     New York   70000
1      Bob   31  Los Angeles   80000
2  Charlie   36      Chicago   90000

In [ ]:
# Dropping Columns
df = df.drop('Age', axis=1)
print(df)

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [ ]:
# Detecting Missing Values

df_with_nan = pd.DataFrame({'A': [1, 2, None], 'B': [4, None, 6]})
print(df_with_nan.isnull())

       A      B
0  False  False
1  False   True
2   True  False

In [ ]:
# Filling Missing Values

filled_df = df_with_nan.fillna(0)  # replaces missing values with a specified value, such as 0.
print(filled_df)

     A    B
0  1.0  4.0
1  2.0  0.0
2  0.0  6.0

In [ ]:
# Dropping Rows with Missing Values

cleaned = df_with_nan.dropna()
print(cleaned)

     A    B
0  1.0  4.0

In [ ]:
# Grouping Data and Calculating Mean

df = pd.DataFrame({'Department': ['HR', 'IT', 'HR', 'IT'],
                   'Salary': [50000, 60000, 45000, 80000]})

print (df)
grouped = df.groupby('Department').mean()
print(grouped)

  Department  Salary
0         HR   50000
1         IT   60000
2         HR   45000
3         IT   80000
             Salary
Department
HR          47500.0
IT          70000.0

In [ ]:
# Applying Custom Functions with apply()

def double_salary(x):
    return x * 2

df['Double Salary'] = df['Salary'].apply(double_salary)
print(df)

  Department  Salary  Double Salary
0         HR   50000         100000
1         IT   60000         120000
2         HR   45000          90000
3         IT   80000         160000

 # Practical Examples with Pandas

In [ ]:
import pandas as pd

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('/employees.csv')

In [ ]:
print("First 5 Rows:\n")
df.head()

First 5 Rows:

   ID           Name Department  Age  Salary Joining_Date
0   1       John Doe         HR   28   50000   2020-05-21
1   2     Jane Smith         IT   34   75000   2019-06-12
2   3    Bob Johnson    Finance   45   85000   2018-07-15
3   4    Alice White         IT   29   72000   2021-01-04
4   5  Charlie Brown  Marketing   32   68000   2019-11-30

In [ ]:
print("Statistical Summary:\n")
df.describe()

Statistical Summary:

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  35.300000  68300.000000
std     3.02765   7.958922  13106.826042
min     1.00000  26.000000  50000.000000
25%     3.25000  29.250000  57250.000000
50%     5.50000  33.000000  69000.000000
75%     7.75000  40.250000  74250.000000
max    10.00000  50.000000  90000.000000

In [ ]:
# Filtering Employees by Department

it_employees = df[df['Department'] == 'IT']
it_employees

,ID,Name,Department,Age,Salary,Joining_Date,Salary_After 5% raise,Salary_After_Raise
1,2,Jane Smith,IT,34,75000,2019-06-12,3750.0,78750.0
3,4,Alice White,IT,29,72000,2021-01-04,3600.0,75600.0
7,8,Linda Taylor,IT,26,64000,2022-02-10,3200.0,67200.0

In [ ]:
# Calculating the Average Salary by Department

average_salary_by_dept = df.groupby('Department')['Salary'].mean()
print("Average Salary by Department:\n")
average_salary_by_dept.head()

Average Salary by Department:

Department
Finance      87500.000000
HR           53000.000000
IT           70333.333333
Marketing    69000.000000
Name: Salary, dtype: float64

In [ ]:
# Sorting Employees by Age in Descending Order

sorted_by_age = df.sort_values(by='Age', ascending=False)
print("Employees Sorted by Age (Descending):\n")
sorted_by_age.head()

Employees Sorted by Age (Descending):

,ID,Name,Department,Age,Salary,Joining_Date,Salary_After 5% raise,Salary_After_Raise
6,7,Mike Davis,Finance,50,90000,2016-08-19,4500.0,94500.0
2,3,Bob Johnson,Finance,45,85000,2018-07-15,4250.0,89250.0
5,6,Eva Green,HR,41,54000,2017-04-22,2700.0,56700.0
8,9,James Wilson,Marketing,38,70000,2020-09-08,3500.0,73500.0
1,2,Jane Smith,IT,34,75000,2019-06-12,3750.0,78750.0

In [ ]:
# Calculating the Number of Employees in Each Department

employee_count_by_dept = df['Department'].value_counts()
print("Number of Employees by Department:\n")
employee_count_by_dept.head()

Number of Employees by Department:

Department
HR           3
IT           3
Finance      2
Marketing    2
Name: count, dtype: int64